### ISSUE TITLE
Window resizing fires zoom event

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#13] opened 2015-08-11 08:49 UTC
Resizing the browser window even a tiny bit seems to fire the zoom event. The map gets much smaller and the zoom ring appears, see here

![resize](https://cloud.githubusercontent.com/assets/4449821/9193798/7cc60e94-4016-11e5-96f1-75b442b6ee4e.jpg)

**Comment by floledermann** [comment] 2015-08-17 15:35
I cannot reproduce this here on Windows, neither in Chrome nor in Firefox - can you post a test case online to investigate?

**Comment by wahlatlas** [comment] 2015-08-17 16:12
The textcase shown above is at
http://vis.uell.net/mapmap/test.html

I could reproduce the behavior with Firefox 40 on both WIndows 7 and OSX 10.8/10.10. Sorry I wasn't aware earlier that this issue does not appear to be present in Chrome (and the map doesn't display at all in IE9 and IE11).

**Comment by floledermann** [comment] 2015-08-18 09:42
Wow, with that simple example you seemed to have triggered a special case where the map scaling mechanism breaks down completely. Scaling SVG and the interaction between the width, height attributes and CSS positioning/sizing is really tricky and inconsistent across browsers...

As a quick workaround I found that if you remove absolute positioning from the SVG element the problem disappears (I never used absolutely positioned maps extensively so far). It is also not happening when the legend is removed from the map.

I am investigating this problem right now, and will update this issue accordingly.

**Comment by floledermann** [comment] 2015-08-18 09:52
Another way to prevent this bug is to set `keepAspectRatio: false` in the mapmap options. This will completely disable the map-resizing mechanism needed for responsive layouts.

**Comment by floledermann** [comment] 2015-08-18 12:24
Fixed in master and new 0.2.5 release. Please verify - also the zoom ring and hoverInfo should work better now...

**Closed as completed by floledermann** 2015-08-18 12:24 UTC
Labels: bug

**Comment by wahlatlas** [comment] 2015-08-18 14:04
Yes, the unintended zoom on resize is fixed, even with absolute positioned elements. The hoverInfo however stopped working altogether with v0.25, see my example (only mapmap.js swapped out)
http://vis.uell.net/mapmap/test_025.html

**Comment by floledermann** [comment] 2015-08-18 14:26
Should be fixed in master and 0.2.6 release - sorry for that!

**Comment by wahlatlas** [comment] 2015-08-18 14:41
Perfect, works like expected
