### ISSUE TITLE
Counter-productive caching in legend generation

### ISSUE THREAD

**Issue by wahlatlas** [floledermann/mapmap.js#30] opened 2015-11-20 18:02 UTC
I can only guess that somewhere in the last few weeks the legend generation code introduced a caching mechanism that has detrimental side effects. Consider this setup where I want to switch between a map with 7 colors and one that has 8 colors:

```
.meta({
    'Variable_A': {
        scale: 'threshold',
        domain: [280,310,340,370,400,430,460],
        color: colorbrewer.Blues[8]
    },
    'Variable_B': {
        scale: 'threshold',
        domain: [275,320,355,385,430,540],
        color: colorbrewer.YlGn[7]
    },
```

right now I start with Variable_A, then switch to Variable_B, but when I switch back to Variable_A only classes 2 to 8 are shown in the legend. The map is colored correctly.

This was not the case up to Nov 4th but started to become an issue Nov 13th.

**Comment by floledermann** [comment] 2015-11-20 19:44
I cannot reproduce this - I added a test case in the examples repo in `test/switch.html` that is similar to yours, but it works correctly. Can you provide a test case online?

**Comment by wahlatlas** [comment] 2015-11-20 20:35
I am deeply sorry to have bothered you with this. It seems, after having taken a break and downloading mapmap.js again all is working now as it should. I might have botched the file somehow as I just download this every once in a while

https://raw.githubusercontent.com/floledermann/mapmap.js/master/mapmap.js

Have a great weekend!

**Comment by wahlatlas** [comment] 2015-11-20 20:55
But you did change something here https://github.com/floledermann/mapmap.js/commit/2505b4cf90fa43e170419c85e17d0af694f64397, could it be related?

**Comment by floledermann** [comment] 2015-11-21 08:29
This was a small bug I discovered when building the test case, where the "undefined" class got assigned to the wrong legendCell - but this should not have anything to do with the number of cells showing...

**Closed as completed by floledermann** 2015-11-21 08:29 UTC

**Comment by wahlatlas** [comment] 2015-11-21 09:00
That was indeed the culprit as I had set the undefined legend to `display: none;` and upon changing back from 7 to 8 classes the lowest class also got assigned "undefined" and thus didn't show

**Comment by floledermann** [comment] 2015-11-21 09:36
Aah, I see - then sorry for not mentioning this change!
